

# This file was *autogenerated* from the file ../exploration/test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1)
import snappy

link = snappy.Link('L12n84')
alex = link.alexander_polynomial(-_sage_const_1 )
print(alex)

